# Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and
create a real matrix product.

In [3]:
import numpy as np
from numpy import random as rd

In [17]:

M,N,A=map(int,input("enter the 3 numbers separated space  in single line: ").split())
matrixA=rd.rand(M,N)
matrixB=rd.rand(N,A)
print("""first matrix :  
""",matrixA)
print("""second matrix:
""",matrixB)

print("""dot product of matrix A and matrix B
""",np.dot(matrixA,matrixB))


enter the 3 numbers separated space  in single line: 4 5 6
first matrix :  
 [[0.68523792 0.19813781 0.83713396 0.72147245 0.16462505]
 [0.84865202 0.48568343 0.40180186 0.74558717 0.2802248 ]
 [0.97865837 0.33382974 0.7251066  0.43006699 0.09285213]
 [0.80880205 0.52315324 0.22641438 0.73354283 0.68213909]]
second matrix:
 [[0.42023222 0.42056552 0.84308837 0.50560842 0.77435259 0.90942197]
 [0.09724402 0.42325064 0.58570063 0.85379662 0.56301311 0.78129785]
 [0.56410084 0.35416398 0.84623419 0.84331931 0.4411163  0.74117748]
 [0.27382339 0.81585127 0.75140817 0.68415127 0.66668173 0.19809918]
 [0.61508853 0.56442344 0.33994463 0.89889899 0.61241248 0.85629103]]
dot product of matrix A and matrix B
 [[1.07826975 1.35006455 2.00026064 1.86318028 1.59325431 1.68232997]
 [1.00703976 1.47123704 1.99547343 1.94459595 1.77652589 1.8367069 ]
 [1.02763464 1.21296888 1.98895021 1.76903258 1.60921511 1.85297093]
 [1.13891586 1.62524416 1.96298198 2.16157162 1.92750526 2.04151793]]


# Problem Statement 2: Write a NumPy program to check if each element of an array of your  choice is composed of digits, lower case letters, and upper case letters only.


In [ ]:
x = [x for x in input("Enter multiple values: ").split()]
x = np.array(x, dtype=str)
print("\nOriginal Array:")
print(x)
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)

# Problem Statement 3: Write a program that reads two space-separated positive integers 𝑋 and 𝑌 as input and perform the following tasks:

In [1]:

def pos(X,Y):
    if X>0 and Y >0:
        list1=[i for i in range(1,16*X,X)]
        list2=[i for i in range(1,16*Y,Y)]
        np1=np.array(list1)
        np2=np.array(list2)
        P=np1.reshape(4,4)
        q=np2.reshape(4,4)
        np3=np.subtract(np1,np2)
        print(np3)
    else:
        print("enter positive number")
X,Y=map(int,input("enter the 2 numbers separated space  in single line: ").split())
pos(X,Y)

enter the 2 numbers separated space  in single line: -7 9
enter positive number


# Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of shape [3 ∗ 3] and perform the following task:


In [13]:
x = [int(x) for x in input("Enter multiple values: ").split()[:9]]
y = [int(x) for x in input("Enter multiple values: ").split()[:9]]
p=np.array(x)
q=np.array(y)
P=p.reshape(3,3)
Q=q.reshape(3,3)
print(np.subtract(P,Q))

Enter multiple values: 23 56 87 3 6 96 4 6 78
Enter multiple values: 12 34 54 7 2 54 6 2 78
[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
